server:
  port: 8100
  error:
    # e.g. when an 500 error is displayed will have the underlying error message
    include-message: always
spring:
  application:
    name: springboot-admin-8
logging:
  file:
    name: logs/springboot-admin-8.log
    max-history: 5
    max-size: 10MB
  level:
    root: INFO
    org.springframework.web: INFO
    com.hackearth: DEBUG
    org.hibernate: INFO
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

